In [1]:
import numpy as np
import pandas as pd
import ssms
#import config
#import dataset_generators

In [6]:
dataset_generators

<module 'ssms.dataset_generators' from '/Users/afengler/OneDrive/project_ssm_simulators/ssm_simulators/ssms/dataset_generators/__init__.py'>

In [4]:
from ssms import basic_simulators
from ssms import dataset_generators

In [3]:
ssms.basic_simulators.simulator(theta = [0, 1, 0.5, 1, 0.5])

AttributeError: module 'ssms' has no attribute 'basic_simulators'

In [13]:
# my_data_config = config.data_generator_config['lan']['cnn']

my_data_config = ssms.config.data_generator_config['lan']['mlp']
my_data_config['dgp_list'] = 'ddm'
my_data_config['n_parameter_sets'] = 100
my_data_config['n_samples'] = 1000

In [14]:
#my_model_config = config.model_config['glob']
my_model_config = ssms.config.model_config['ddm']

In [15]:
my_dataset_generator = ssms.dataset_generators.data_generator(generator_config = my_data_config,
                                                              model_config = my_model_config)

n_cpus:  6
checking:  data/lan_mlp/


In [6]:
x = my_dataset_generator.generate_data_training_uniform(save = False)

simulation round: 1  of 10
[2.8337805 1.0352426 0.5291598 1.4856405][2.9552577 2.494943  0.7956801 0.696128 ][1.8896824  0.7291233  0.5614472  0.38774565][-0.54592204  2.1856751   0.25565964  1.496582  ][-0.4735248   1.123348    0.4814363   0.87110215][-0.9121251   1.5798955   0.40213048  1.4019119 ]





tmp_n_ctmp_n_ctmp_n_ctmp_n_ctmp_n_ctmp_n_c





00110
1



tmp_n_c
tmp_n_ctmp_n_ctmp_n_ctmp_n_c


tmp_n_c

11
001


0


[0][0][0][0][0]
[0]




[1.5243698  1.0695978  0.62848085 1.031072  ][-2.1806653   1.7398324   0.4871597   0.08399034][0.480432   0.39834508 0.56788    1.6273229 ][0.43563387 1.623742   0.40735906 0.26676834][-0.07178151  1.3074807   0.3965987   1.715993  ][1.9563421  2.4185805  0.48709163 0.2590591 ]




tmp_n_ctmp_n_c
tmp_n_ctmp_n_ctmp_n_ctmp_n_c




0
10110



tmp_n_c

tmp_n_ctmp_n_ctmp_n_ctmp_n_c

tmp_n_c10



0
1
10


[0]
[0][0]
[0]
[0][0]



[1.6732024 2.299144  0.5657896 1.8717067][-1.8321213   1.3830258   0.81450653  0.23316287][-1.7982817   1.8672736   0.671

In [5]:
my_output = my_dataset_generator.generate_data_nested(save = False)

   0.01748262,  0.        ],
       [-0.2008512 ,  0.48497012,  0.78317183,  1.        ,  0.        ,
         0.96895134,  0.        ]], dtype=float32)}, {'data': array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        ...,
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        ...,
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        ...,
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       ...,

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        ...,
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        ...,
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        ...,
        [0., 0.],
        [0., 0.],
        [0., 0.]]], dtype=float32), 'label_components': array([[0., 0., 0.],
       [0., 0., 0.],
       

In [5]:
my_output = my_dataset_generator.generate_data_ratio_estimator(save = False)

Starting simulations
simulations finished!
simulations finished!simulations finished!

simulations finished!
simulations finished!simulations finished!

simulations finished!
simulations finished!simulations finished!

simulations finished!
simulations finished!
simulations finished!


In [8]:
my_output['labels']

array([0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1.,
       1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0.,
       0., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0.,
       1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       0., 1., 0., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0.],
      dtype=float32)

In [ ]:
my_dataset_generator.model_config

In [8]:
x['data'].shape

(10, 512, 2)

In [9]:
x['labels'].shape

(10, 4)

In [10]:
my_output['label_parameters']

array([[ 1.2226119 ,  0.37123147,  0.5904053 ,  1.6807697 ,  0.        ,
         1.0837663 ,  0.        ],
       [ 2.9925056 ,  1.3653069 ,  0.1604542 ,  1.2743086 ,  0.18776555,
         1.2324505 ,  0.        ],
       [ 2.477468  ,  0.58937293,  0.3375957 ,  1.2296201 ,  0.82703817,
         0.92556745,  1.0006771 ],
       [-0.5683042 ,  0.43178543,  0.5617197 ,  1.1424209 ,  0.01943262,
         1.4299839 ,  0.        ],
       [-1.805324  ,  0.9111644 ,  0.5896453 ,  1.896022  ,  0.        ,
         1.6689351 ,  0.        ],
       [-1.7950133 ,  1.206874  ,  0.64769906,  1.4530326 ,  0.7132122 ,
         0.93900985,  0.        ],
       [ 1.1343992 ,  0.8687558 ,  0.489402  ,  1.9120643 ,  0.        ,
         0.5533016 ,  0.        ],
       [-0.55500275,  1.4295069 ,  0.6387958 ,  1.        ,  0.56790733,
         0.62682825,  0.83169496],
       [-0.0092219 ,  0.86031497,  0.42054382,  1.        ,  0.        ,
         0.01748262,  0.        ],
       [-0.2008512 ,  0.4849